spring:
  liquibase:
    enabled: true
    change-log: classpath:announcementdb/changelog/changelog-master.yml
    default-schema: ms_announcement_schema
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock