version: '3.8'

services:
  postgres-service:
    hostname: postgres
    image: postgres
    container_name: postgres-container
    restart: always
    networks:
      - my_network
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-service:
    hostname: redis
    image: redis
    container_name: redis-container
    networks:
      - my_network
    ports:
      - '6371:6379'
    volumes:
      - redis_data:/data

  ms-user-app-service:
    hostname: ms-user-app
    image: ms-user-app
    container_name: ms-user-app-container
    networks:
      - my_network
    ports:
      - '8082:8082'
    depends_on:
      - postgres-service
    environment:
      DB_CONNECTION_USERNAME: postgres
      DB_CONNECTION_PASSWORD: password
      DB_CONNECTION_PORT: '5432'
      DB_CONNECTION_IP: postgres-service

  ms-announcement-app-service:
    hostname: ms-announcement-app
    image: ms-announcement-app
    container_name: ms-announcement-app-container
    networks:
      - my_network
    ports:
      - '8081:8081'
    depends_on:
      - postgres-service
    environment:
      DB_CONNECTION_USERNAME: postgres
      DB_CONNECTION_PASSWORD: password
      DB_CONNECTION_PORT: '5432'
      DB_CONNECTION_IP: postgres-service

volumes:
  redis_data: { }
  postgres_data: { }

networks:
  my_network: { }