version: '3.8'

services:
  postgres-service:
    hostname: postgres
    image: postgres
    container_name: postgres-container
    restart: always
    networks:
      - my_network
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-service:
    hostname: redis
    image: redis
    container_name: redis-container
    networks:
      - my_network
    ports:
      - '6371:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: { }
  postgres_data: { }

networks:
  my_network: { }